<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EstadosTableSeeder extends Seeder
{
    public function run(): void
    {
        // Vaciar la tabla para evitar duplicados
        DB::table('estados')->truncate();

        // Insertar los 32 estados
        DB::table('estados')->insert([
            [
                'id'             => 1,
                'nombre'         => 'Aguascalientes',
                'fecha_creacion' => '2020-07-20 17:21:04',
                'fecha_edicion'  => null,
                'id_usuario'     => 1,
                'fecha_edit'     => '2020-07-22 15:47:56',
                'status'         => 1,
            ],
            [
                'id'             => 2,
                'nombre'         => 'Baja California',
                'fecha_creacion' => '2020-07-20 17:21:04',
                'fecha_edicion'  => null,
                'id_usuario'     => 1,
                'fecha_edit'     => '2020-07-22 18:22:30',
                'status'         => 1,
            ],
            [
                'id'             => 3,
                'nombre'         => 'Baja California Sur',
                'fecha_creacion' => '2020-07-20 17:21:04',
                'fecha_edicion'  => null,
                'id_usuario'     => null,
                'fecha_edit'     => null,
                'status'         => 1,
            ],
            [
                'id'             => 4,
                'nombre'         => 'Campeche',
                'fecha_creacion' => '2020-07-20 17:21:04',
                'fecha_edicion'  => null,
                'id_usuario'     => null,
                'fecha_edit'     => null,
                'status'         => 1,
            ],
            [
                'id'             => 5,
                'nombre'         => 'Chiapas',
                'fecha_creacion' => '2020-07-20 17:21:04',
                'fecha_edicion'  => null,
                'id_usuario'     => null,
                'fecha_edit'     => null,
                'status'         => 1,
            ],
            [
                'id'             => 6,
                'nombre'         => 'Chihuahua',
                'fecha_creacion' => '2020-07-20 17:21:04',
                'fecha_edicion'  => null,
                'id_usuario'     => null,
                'fecha_edit'     => null,
                'status'         => 1,
            ],
            [
                'id'             => 7,
                'nombre'         => 'Coahuila',
                'fecha_creacion' => '2020-07-20 17:21:04',
                'fecha_edicion'  => null,
                'id_usuario'     => null,
                'fecha_edit'     => null,
                'status'         => 1,
            ],
            [
                'id'             => 8,
                'nombre'         => 'Colima',
                'fecha_creacion' => '2020-07-20 17:21:04',
                'fecha_edicion'  => '2018-01-05 18:09:39',
                'id_usuario'     => null,
                'fecha_edit'     => null,
                'status'         => 1,
            ],
            [
                'id'             => 9,
                'nombre'         => 'Ciudad de México',
                'fecha_creacion' => '2020-07-20 17:21:04',
                'fecha_edicion'  => null,
                'id_usuario'     => null,
                'fecha_edit'     => null,
                'status'         => 1,
            ],
            [
                'id'             => 10,
                'nombre'         => 'Durango',
                'fecha_creacion' => '2020-07-20 17:21:04',
                'fecha_edicion'  => null,
                'id_usuario'     => null,
                'fecha_edit'     => null,
                'status'         => 1,
            ],
            [
                'id'             => 11,
                'nombre'         => 'Guanajuato',
                'fecha_creacion' => '2020-07-20 17:21:04',
                'fecha_edicion'  => null,
                'id_usuario'     => null,
                'fecha_edit'     => null,
                'status'         => 1,
            ],
            [
                'id'             => 12,
                'nombre'         => 'Guerrero',
                'fecha_creacion' => '2020-07-20 17:21:04',
                'fecha_edicion'  => null,
                'id_usuario'     => null,
                'fecha_edit'     => null,
                'status'         => 1,
            ],
            [
                'id'             => 13,
                'nombre'         => 'Hidalgo',
                'fecha_creacion' => '2020-07-20 17:21:04',
                'fecha_edicion'  => null,
                'id_usuario'     => null,
                'fecha_edit'     => null,
                'status'         => 1,
            ],
            [
                'id'             => 14,
                'nombre'         => 'Jalisco',
                'fecha_creacion' => '2020-07-20 17:21:04',
                'fecha_edicion'  => null,
                'id_usuario'     => null,
                'fecha_edit'     => null,
                'status'         => 1,
            ],
            [
                'id'             => 15,
                'nombre'         => 'México',
                'fecha_creacion' => '2020-07-20 17:21:04',
                'fecha_edicion'  => null,
                'id_usuario'     => null,
                'fecha_edit'     => null,
                'status'         => 1,
            ],
            [
                'id'             => 16,
                'nombre'         => 'Michoacán',
                'fecha_creacion' => '2020-07-20 17:21:04',
                'fecha_edicion'  => null,
                'id_usuario'     => null,
                'fecha_edit'     => null,
                'status'         => 1,
            ],
            [
                'id'             => 17,
                'nombre'         => 'Morelos',
                'fecha_creacion' => '2020-07-20 17:21:04',
                'fecha_edicion'  => null,
                'id_usuario'     => null,
                'fecha_edit'     => null,
                'status'         => 1,
            ],
            [
                'id'             => 18,
                'nombre'         => 'Nayarit',
                'fecha_creacion' => '2020-07-20 17:21:04',
                'fecha_edicion'  => null,
                'id_usuario'     => null,
                'fecha_edit'     => null,
                'status'         => 1,
            ],
            [
                'id'             => 19,
                'nombre'         => 'Nuevo León',
                'fecha_creacion' => '2020-07-20 17:21:04',
                'fecha_edicion'  => null,
                'id_usuario'     => null,
                'fecha_edit'     => null,
                'status'         => 1,
            ],
            [
                'id'             => 20,
                'nombre'         => 'Oaxaca',
                'fecha_creacion' => '2020-07-20 17:21:04',
                'fecha_edicion'  => null,
                'id_usuario'     => null,
                'fecha_edit'     => null,
                'status'         => 1,
            ],
            [
                'id'             => 21,
                'nombre'         => 'Puebla',
                'fecha_creacion' => '2020-07-20 17:21:04',
                'fecha_edicion'  => null,
                'id_usuario'     => null,
                'fecha_edit'     => null,
                'status'         => 1,
            ],
            [
                'id'             => 22,
                'nombre'         => 'Querétaro',
                'fecha_creacion' => '2020-07-20 17:21:04',
                'fecha_edicion'  => null,
                'id_usuario'     => null,
                'fecha_edit'     => null,
                'status'         => 1,
            ],
            [
                'id'             => 23,
                'nombre'         => 'Quintana Roo',
                'fecha_creacion' => '2020-07-20 17:21:04',
                'fecha_edicion'  => null,
                'id_usuario'     => null,
                'fecha_edit'     => null,
                'status'         => 1,
            ],
            [
                'id'             => 24,
                'nombre'         => 'San Luis Potosí',
                'fecha_creacion' => '2020-07-20 17:21:04',
                'fecha_edicion'  => null,
                'id_usuario'     => null,
                'fecha_edit'     => null,
                'status'         => 1,
            ],
            [
                'id'             => 25,
                'nombre'         => 'Sinaloa',
                'fecha_creacion' => '2020-07-20 17:21:04',
                'fecha_edicion'  => null,
                'id_usuario'     => null,
                'fecha_edit'     => null,
                'status'         => 1,
            ],
            [
                'id'             => 26,
                'nombre'         => 'Sonora',
                'fecha_creacion' => '2020-07-20 17:21:04',
                'fecha_edicion'  => null,
                'id_usuario'     => null,
                'fecha_edit'     => null,
                'status'         => 1,
            ],
            [
                'id'             => 27,
                'nombre'         => 'Tabasco',
                'fecha_creacion' => '2020-07-20 17:21:04',
                'fecha_edicion'  => null,
                'id_usuario'     => null,
                'fecha_edit'     => null,
                'status'         => 1,
            ],
            [
                'id'             => 28,
                'nombre'         => 'Tamaulipas',
                'fecha_creacion' => '2020-07-20 17:21:04',
                'fecha_edicion'  => null,
                'id_usuario'     => null,
                'fecha_edit'     => null,
                'status'         => 1,
            ],
            [
                'id'             => 29,
                'nombre'         => 'Tlaxcala',
                'fecha_creacion' => '2020-07-20 17:21:04',
                'fecha_edicion'  => null,
                'id_usuario'     => null,
                'fecha_edit'     => null,
                'status'         => 1,
            ],
            [
                'id'             => 30,
                'nombre'         => 'Veracruz',
                'fecha_creacion' => '2020-07-20 17:21:04',
                'fecha_edicion'  => null,
                'id_usuario'     => null,
                'fecha_edit'     => null,
                'status'         => 1,
            ],
            [
                'id'             => 31,
                'nombre'         => 'Yucatán',
                'fecha_creacion' => '2020-07-20 17:21:04',
                'fecha_edicion'  => null,
                'id_usuario'     => null,
                'fecha_edit'     => null,
                'status'         => 1,
            ],
            [
                'id'             => 32,
                'nombre'         => 'Zacatecas',
                'fecha_creacion' => '2020-07-20 17:21:04',
                'fecha_edicion'  => null,
                'id_usuario'     => null,
                'fecha_edit'     => null,
                'status'         => 1,
            ],
        ]);
    }
}
